In [ ]:
,cprint('test')

test


In [ ]:
import torch
print(torch.__version__)

2.0.1+cu118


In [ ]:
scalar = torch.tensor(7)

In [ ]:
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
test = torch.rand(3, 5)
test

tensor([[0.7108, 0.5823, 0.0378, 0.4891, 0.5981],
        [0.0441, 0.7808, 0.0645, 0.1867, 0.1868],
        [0.3045, 0.8567, 0.6596, 0.7577, 0.4309]])

In [ ]:
random_image = torch.rand(224, 224, 3)
random_image.ndim, random_image.shape

(3, torch.Size([224, 224, 3]))

In [ ]:
mask = torch.zeros(size=(3,1,5))

In [ ]:
mask

tensor([[[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]]])

In [ ]:
temp = torch.rand(size=(3,1,5))

In [ ]:
temp

tensor([[[0.8692, 0.6126, 0.4318, 0.5007, 0.8007]],

        [[0.7020, 0.0960, 0.0414, 0.6812, 0.2016]],

        [[0.7301, 0.8477, 0.2852, 0.9458, 0.8829]]])

In [ ]:
temp + mask

tensor([[[0.8692, 0.6126, 0.4318, 0.5007, 0.8007]],

        [[0.7020, 0.0960, 0.0414, 0.6812, 0.2016]],

        [[0.7301, 0.8477, 0.2852, 0.9458, 0.8829]]])

In [ ]:
temp * mask

tensor([[[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]]])

In [ ]:
temp = torch.arange(start=1, end=11, step=1)
temp

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
zeros = torch.zeros_like(temp)
zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
test = torch.tensor([[1,2.35,3],[3,2,1]],
                       dtype=torch.float32,
                       device="cpu")
test.dtype

torch.float32

In [ ]:
tempo = torch.ones_like(kirkhar, dtype=torch.int)
tempo * kirkhar

tensor([[1.0000, 2.3500, 3.0000],
        [3.0000, 2.0000, 1.0000]])

In [ ]:
some_tensor = torch.rand(size=(3, 4),
                         dtype=torch.float32,)
some_tensor.dtype

torch.float32

In [ ]:
some_other_tensor = torch.rand(size=(4,3))
some_other_tensor

tensor([[0.7237, 0.6184, 0.7921],
        [0.6813, 0.1352, 0.7639],
        [0.6039, 0.8400, 0.1188],
        [0.2507, 0.1151, 0.3737]])

In [ ]:
torch.matmul(some_tensor, some_other_tensor)

tensor([[1.0759, 0.5321, 1.0912],
        [1.2740, 0.8102, 1.1665],
        [1.0941, 0.9801, 0.8318]])

In [ ]:
some_tensor, some_tensor.min()

(tensor([[0.3347, 0.9966, 0.2122, 0.1057],
         [0.2901, 0.9067, 0.5390, 0.4817],
         [0.4071, 0.3627, 0.7565, 0.3809]]),
 tensor(0.1057))

In [ ]:
some_tensor, some_tensor.argmin()

(tensor([[0.3347, 0.9966, 0.2122, 0.1057],
         [0.2901, 0.9067, 0.5390, 0.4817],
         [0.4071, 0.3627, 0.7565, 0.3809]]),
 tensor(3))

In [ ]:
some_other_tensor, some_other_tensor.max(), some_other_tensor.argmax()

(tensor([[0.7237, 0.6184, 0.7921],
         [0.6813, 0.1352, 0.7639],
         [0.6039, 0.8400, 0.1188],
         [0.2507, 0.1151, 0.3737]]),
 tensor(0.8400),
 tensor(7))

In [ ]:
some_other_tensor[3, 2]

tensor(0.3737)

In [ ]:
import torch
torch.manual_seed(5)
random_tensor_x = torch.rand(size=(3,4))
random_tensor_y = torch.rand(size=(3,4))
random_tensor_x, random_tensor_y

(tensor([[0.8303, 0.1261, 0.9075, 0.8199],
         [0.9201, 0.1166, 0.1644, 0.7379],
         [0.0333, 0.9942, 0.6064, 0.5646]]),
 tensor([[0.0724, 0.6593, 0.7150, 0.5793],
         [0.9809, 0.6502, 0.0566, 0.9201],
         [0.6698, 0.2615, 0.0407, 0.7850]]))

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
tensor = torch.tensor([1, 2, 3], device='cuda')
tensor, tensor.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [ ]:
import torch
import sklearn
from sklearn.datasets import make_circles
from torch import nn
import pandas as pd
import matplotlib.pyplot as plt


n_samples = 1000

X, Y = make_circles(n_samples, noise = 0.05, random_state=5)

# plt.scatter(x=X[:, 0], y=X[:, 1], c=Y, cmap=plt.cm.RdYlBu)
# X.shape, Y.shape



((1000, 2), (1000,))